[package]
name = "adventofcode-2021"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.3"
bitvec = "0.22.3"
regex = "1.5.4"
rayon = "1.5.1"
